language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install git+git://github.com/kytos/python-openflow.git@develop
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#kytos"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
after_success:
    coveralls
